version: '3.3'
services:
  postgresql:
    container_name: postgres-servidor
    image: postgres:16-bullseye

    networks:
      - redinterna
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql docker.io/library/postgres:16-bullseye
      - ./_data:/var/lib/postgresql
    restart: always

networks:
  redinterna: